# Creates example user, creates wallet and gets all its current transactions


POST  localhost:8000/user
accept: application/json

> {% client.global.set("api_key", response.body.api_key); %}
###

POST localhost:8000/wallet
accept: application/json
api-key: {{ api_key }}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "error code not 201");
});
client.global.set("address", response.body.address); %}

###


###
GET localhost:8000/wallet/{{address}}
accept: application/json
api-key: {{api_key}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "error code not 200");
});
%}
###

GET localhost:8000/wallet/{{address}}/transaction
accept: application/json
api-key: {{api_key}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "error code not 209");
});
%}

###