class Config:
    BTC_TO_SATOSHI = pow(10, 8)

    DEFAULT_AMOUNT_ON_REGISTRATION = 1 * BTC_TO_SATOSHI

    DEFAULT_COMMISSION_RATE = 0.015

    MAX_WALLETS_TO_USER = 3

    ADMIN_KEY = "UNBROKEN"

    DATABASE_NAME = "sqlite.db"
